### ISSUE TITLE
System Cannot Find the File Specified

### ISSUE THREAD

**Issue by BraveryrevarB** [flyingleafe/uroman-python#1]
Hello, I am very interested in this project, but when I use it, I will have the following errors. I also installed Perl in my computer.

Traceback (most recent call last):
  File "D:\PycharmProjects\MultiModal-NER\force_alignment_chinese.py", line 6, in <module>
    romanized_zh = uroman("关 服务 高端 产品 仍 处于 供不应求 的 局面", language="zh")
  File "D:\anaconda3\envs\multimodal\lib\site-packages\uroman\__init__.py", line 21, in uroman
    process = subprocess.Popen(command, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "D:\anaconda3\envs\multimodal\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\anaconda3\envs\multimodal\lib\subprocess.py", line 1327, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

I am using python=3.8，how can I fix this problem？
Thanks！

**Comment by BraveryrevarB** [comment]
I solve it by reinstalling Perl.
